### ISSUE TITLE
添加一个需求

### ISSUE THREAD

**Issue by flydeemon** [naihe138/vue-picker#1]
1.能不能加一个黑色半透明的遮罩层？用户只要点击遮罩层就关闭该组件（不保存）
2.能不能初始化默认数据，例如（广东省广州市天河区）这样的，默认就选择好了。当打开该组件的时候，也是从默认数据的位置开始选择

**Comment by naihe138** [comment]
半透明自己自定义就可以了，自定义显示对象已经加上，谢谢提出宝贵的意见
