### ISSUE TITLE
第二次点击的时候获取不到值

### ISSUE THREAD

**Issue by 547377507** [naihe138/vue-picker#2]
第一次我选择的是下午-2，然后再次点击打开picker框中的默认值回到了第一行，并且这个时候点击确定获取不到值，值没有改变
![image](https://user-images.githubusercontent.com/13267376/35445050-613072e2-02eb-11e8-855e-b23c18b7339f.png)

**Comment by Heiqing** [comment]
我也是遇到这个情况

**Comment by naihe138** [comment]
http://gitblog.naice.me/vue-picker/arearSelect/index.html#/

可以了
