### ISSUE TITLE
首次弹出时点击内容会有bug

### ISSUE THREAD

**Issue by lancelot666** [naihe138/vue-picker#23]
首次弹出时，若单击text内容后再点击确定（没有滚动动作），则会出现获取到undefined值。此时需要滚动一下内容才能正确取到值

**Comment by lancelot666** [comment]
问题已发现，场景是单列使用时：若弹出picker后，点击默认text再点击确定按钮。state中的select1变量会被移除。导致获取不到所点击的text。
目前我在finish函数中加入了判断：
finish: function (e) {
      	if(!(JSON.parse(JSON.stringify(this.selects)).hasOwnProperty('select1'))){
      		this.selects.select1 = this.pData1[0];
      	}
      	if(!(JSON.parse(JSON.stringify(this.selects)).hasOwnProperty('select2'))){
      		this.selects.select2 = this.pData2[0];
      	}
      	if(!(JSON.parse(JSON.stringify(this.selects)).hasOwnProperty('select3'))){
      		this.selects.select3 = this.pData3[0];
      	}
        this.$emit('confirm', JSON.parse(JSON.stringify(this.selects)))
        e.preventDefault()
      },

**Comment by naihe138** [comment]
已修复
