### ISSUE TITLE
feature: 提供设置可变的初始选中项

### ISSUE THREAD

**Issue by iyolee** [naihe138/vue-picker#29]
defaultIndex 可设置初始选中项，但有时数据是根据网络请求回来的数据动态初始化。

**Comment by ganganlee** [comment]
同问 如何动态设置defaultIndex  目前在组件创建时修改了defaultIndex 不生效

**Comment by naihe138** [comment]
@iyolee  @ganganlee  已修复

**Comment by naihe138** [comment]
defaultIndex = [1,2,3]

**Comment by ganganlee** [comment]
您好：
&nbsp; &nbsp; 三列数据联动通过异步获取的数据来修改defaultIndex的值我这边还是存在问题，第一列数据能设置上，后面两列都是为0
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"naice"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午2:24
收件人:&nbsp;"naihe138/vue-picker"<vue-picker@noreply.github.com&gt;;
抄送:&nbsp;"thousand"<www.nolulu@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [naihe138/vue-picker] feature: 提供设置可变的初始选中项 (#29)




@iyolee  @ganganlee  已修复
