### ISSUE TITLE
计算选中的index需要结合rowNumber来计算

### ISSUE THREAD

**Issue by BugKun** [naihe138/vue-picker#36]
计算选中的index需要结合rowNumber来计算

https://github.com/naihe138/vue-picker/blob/340564a8dcc333503dd2c5d3dc71255e48fa3449/src/list.vue#L127

当rowNumber=3时，轻轻拖动list半格，使其回落到原始位置，但是实际的index却为下一个。
```javascript
index = Math.floor(this.rowNumber / 2) - index
```

**Comment by naihe138** [comment]
@BugKun 谢谢指出问题，新版本已经修复了
