### ISSUE TITLE
pickData赋值 问题

### ISSUE THREAD

**Issue by 13718003748** [naihe138/vue-picker#38]
pickData赋值必须在data初始化里面吗，默认pickData为空，在methods里面 调用接口赋值给pickData无效是什么原因？之后再赋值不行吗？求解，谢谢！

**Comment by xpader** [comment]
是的我也是碰到这个问题，因为值要从后端获取，所以这种情况根本没法使用，光是这种情况，这个组件的实用性就下降了一半。

**Comment by xpader** [comment]
我找遍了网络没有找到一个像样的满足需求的插件，于是使用已经在用的 mint-ui 的 picker + popup 再加上自己的一些定制做了一个。

**Comment by naihe138** [comment]
@13718003748 @xpader  很抱歉，已经修复了
