### ISSUE TITLE
地理位置级联选择初始化位置错误

### ISSUE THREAD

**Issue by machengda89** [naihe138/vue-picker#39]
![image](https://user-images.githubusercontent.com/6835957/78106975-2914d880-7427-11ea-824c-0a9f4a6e06ee.png)

defaultIndex:[index1, index2, index3]

index2,index3 均没有生效

**Comment by naihe138** [comment]
要设置layer @machengda89

**Comment by machengda89** [comment]
看清楚问题，你的demo就存在初始化位置问题 
![image](https://user-images.githubusercontent.com/6835957/79103441-24dda900-7d9f-11ea-9c00-70e5cd4072d8.png)

@naihe138
