### ISSUE TITLE
多级联动 defaultIndex 有问题

### ISSUE THREAD

**Issue by sjlei** [naihe138/vue-picker#42]
选择了一条数据后，保存到数据库里，然后再编辑赋值的时候，没有正确显示。只有第一列是正常的，后面两列没有联动显示。

![image](https://user-images.githubusercontent.com/34293221/82403179-cd62e500-9a90-11ea-8742-bc613f8cd114.png)

![image](https://user-images.githubusercontent.com/34293221/82403209-de135b00-9a90-11ea-8fb7-aaf5ec9e7a81.png)

![image](https://user-images.githubusercontent.com/34293221/82403236-eff4fe00-9a90-11ea-98fb-ac60988b398a.png)

省市区的数据用的不是组件提供的，而是我们自己的，格式严格遵守了下面的格式
```
[
   ……
   {
       "label": "山东省",
       "value": "370000",
       "children": [……] 
   },
   ……
]
```

**Comment by naihe138** [comment]
已修复
