### ISSUE TITLE
iOS Safari 显示bug

### ISSUE THREAD

**Issue by leon2011leon** [naihe138/vue-picker#43]
![IMG_6870](https://user-images.githubusercontent.com/1294421/84240163-312c7b00-ab30-11ea-9943-b45a3237e4ae.PNG)
运行官网demo，在iOS上显示存在问题，底部有部分被遮挡，如图
iPhone X 13.2.3

**Comment by naihe138** [comment]
已经修复了。谢谢提出建议。
