### ISSUE TITLE
执行build之后报ERROR，急求帮助

### ISSUE THREAD

**Issue by CharlesJoyce** [naihe138/vue-picker#46]
**### **ERROR in static/js/2.1b3865265f9636d24945.js from UglifyJs**
Unexpected token: name (c) [./~/vue-pickers/lib/vue-picker.js:1,1307][static/js/2.1b3865265f9636d24945.js:4123,1267]

ERROR in static/js/3.977876d7ccb1a425ac0a.js from UglifyJs
Unexpected token: name (c) [./~/vue-pickers/lib/vue-picker.js:1,1307][static/js/3.977876d7ccb1a425ac0a.js:2398,1267]**

package.json : "vue-pickers": "^2.5.1"

**Comment by naihe138** [comment]
这么写`vue-pickers/lib/vue-picker.js`

**Comment by naihe138** [comment]
@CharlesJoyce   ./~/vue-pickers/lib/vue-picker.js 你这个路径是哪里来的？

**Comment by vge-R** [comment]
俺也是这样, run的时候没有错,build就报错了
import VuePicker from 'vue-pickers'
这样引用的

ERROR in static/js/add.848c1ce73dd9b59a1d20.min.js from UglifyJs
SyntaxError: Unexpected token: name (c) [./~/vue-pickers/lib/vue-picker.js:1,1307]

**Comment by akFace** [comment]
> 俺也是这样, run的时候没有错,build就报错了
> import VuePicker from 'vue-pickers'
> 这样引用的
> 
> ERROR in static/js/add.848c1ce73dd9b59a1d20.min.js from UglifyJs
> SyntaxError: Unexpected token: name (c) [./~/vue-pickers/lib/vue-picker.js:1,1307]

解决了吗

**Comment by akFace** [comment]
解决了，要在webpack配置babel-loader中加上不包括它
 ``
{
	test: /\.js$/,
	loader: 'babel-loader',
	exclude (file) {
	  if (
	    file.includes('node_modules') &&
	    !file.includes('vue-pickers')
	  ) {
	    return true
	  }
	  return false
	}
 }
``
