### ISSUE TITLE
普通网页直接引用不显示toolbar

### ISSUE THREAD

**Issue by mcc-like-thinking** [naihe138/vue-picker#52]

**Comment by mcc-like-thinking** [comment]
![2](https://user-images.githubusercontent.com/15810212/90000701-122e9e80-dcc3-11ea-8aa1-a3d418ab3697.png)

**Comment by mcc-like-thinking** [comment]
![1597225049(1)](https://user-images.githubusercontent.com/15810212/90000788-2b374f80-dcc3-11ea-9579-aac66d42fc2e.png)
![2](https://user-images.githubusercontent.com/15810212/90000805-30949a00-dcc3-11ea-81f2-19b78b94fd6f.png)

**Comment by naihe138** [comment]
https://codesandbox.io/s/suspicious-bhabha-lb6nz?file=/src/App.vue

**Comment by naihe138** [comment]
之类是可以的

**Comment by naihe138** [comment]
打开调试器看看？？

**Comment by naihe138** [comment]
@mcc-like-thinking

**Comment by naihe138** [comment]
不行可以加我微信 我帮你看看  naihe2014

**Comment by mcc-like-thinking** [comment]
你好，我找到原因了，直接引用的话，props不能用驼峰式，需要写成小写，用 "-" 隔开；

**Comment by mcc-like-thinking** [comment]
你好，我找到原因了，直接引用的话，props不能用驼峰式，需要写成小写，用 "-" 隔开；






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naihe138/vue-picker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午5:28
收件人:&nbsp;"naihe138/vue-picker"<vue-picker@noreply.github.com&gt;;
抄送:&nbsp;"mcc"<595004514@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [naihe138/vue-picker] 普通网页直接引用不显示toolbar (#52)





 
@mcc-like-thinking
