### ISSUE TITLE
在手机上显示列表项位置错位

### ISSUE THREAD

**Issue by GJune** [naihe138/vue-picker#53]
当列表中的选项过多时，越往下的选项位置错位越严重。可以看下面这个截图，在demo中，最后一个选项的显示位置明显靠上。当有上百上百个选项时，错位非常严重，显示选中A选项，实际选中的确实B选项。

在PC端没有这个问题，只在移动端存在

![微信图片_20200904185342](https://user-images.githubusercontent.com/3352183/92231894-1de73c80-eee0-11ea-86ab-6be57640e483.jpg)

**Comment by naihe138** [comment]
啥手机？？？我在ios上没有哟

**Comment by GJune** [comment]
安卓手机的微信里，小米，华为，三星多台手机都试了
