### ISSUE TITLE
移动问题

### ISSUE THREAD

**Issue by carrey360** [naihe138/vue-picker#6]
https://github.com/naihe138/vue-picker/blob/bf32c93094ab1e746851089840361d304f966c85/lib/picker.vue#L195
这句话是什么意思呢，我现在布局用的是rem 来布局的，你这种滑动后给他加的top和transfrom 属性改成相应的单位后不生效，能否做成获取tooth 自己的高度，这样就不会根据布局不同里面相应的内容做大的改动呢？

**Comment by naihe138** [comment]
1.1.2版修复了哟，请您更新到1.1.2
