### ISSUE TITLE
setTop 问题

### ISSUE THREAD

**Issue by wqdegege** [naihe138/vue-picker#7]
this.pData2是object，但是验证却是用的array

          if(defaultData[1] && defaultData[1].value) {
            for (var i = 0, len = this.pData2.length; i < len; i++) {
              if (this.pData2[i].value == defaultData[1].value) {
                pos2 = -(i*2)
                break
              }
            }
            this.selects.select2 = defaultData[1]
            city.setAttribute('top', pos2 + 'em');
            city.style["-webkit-transform"] = 'translate3d(0,' + pos2 + 'em,0)';
          }

**Comment by naihe138** [comment]
1.1.2版修复了哟，请您更新到1.1.2
